name: Auto Update

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes (GitHub minimum)
  workflow_dispatch:         # allows manual run from the Actions tab

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Make a change
        run: |
          echo "Updated at $(date -u)" >> timestamp.txt

      - name: Commit and push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Auto update $(date -u)" || echo "No changes to commit"
          git push
